In [20]:
import numpy as np
# Membuat Vektor
a = np.array([1,2,3,4,5])
b = np.array([1.2,2.3,3.5,4.7])
print(b)

# Membuat vektor dari range
c = np.arange(1,10,2)
print(c)

# Membuat Linspace / Membagi sama rata
d = np.linspace(1,10,4)
print(d)

# Membuat Matrix
e = np.array([[1,2,3],[4,5,6]])
print(e)

# matrix nilai nol
nol = np.zeros((4,4))
print(nol)

# matrix nilai satu
one = np.ones((4,4))
print(one)

# Matrix identitas
mat = np.eye(5)
mat1 = np.identity(5)
print(mat1)

[1.2 2.3 3.5 4.7]
[1 3 5 7 9]
[ 1.  4.  7. 10.]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
# ELEMENTWISE OPERATION
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])
hasil = a*b
hasil = a+b
hasil = a**b
print(hasil)

c = np.array([[1,2,3],[4,5,6]])
d = np.array([[1,2,3],[4,5,6]])
print(c+d)

[   1    4   27  256 3125]
[[ 2  4  6]
 [ 8 10 12]]


In [36]:
# Perkalian Matrix
c = np.array([(1,2),(2,3)])
d = np.ones([2,2])
print(np.dot(d,c))
print(d.dot(c))

[[3. 5.]
 [3. 5.]]
[[3. 5.]
 [3. 5.]]


In [53]:
# Transpose matrix
matrix = np.array(([1,2,3],[1,2,3]))
print(matrix)
a = matrix.transpose() #tidak merubah
a = np.transpose(matrix)
a = matrix.T
print(a)
print(matrix.shape)

# flatten / vector baris
print(a.ravel())
print(np.ravel(a))

# reshape matrix
print(matrix.reshape(3,2)) #tidak merubah
print(matrix.shape)

# reshape matrix
matrix.resize(3,2) #merubah
print(matrix)
print(matrix.shape)

[[1 2 3]
 [1 2 3]]
[[1 1]
 [2 2]
 [3 3]]
(2, 3)
[1 1 2 2 3 3]
[1 1 2 2 3 3]
[[1 2]
 [3 1]
 [2 3]]
(2, 3)
[[1 2]
 [3 1]
 [2 3]]
(3, 2)


In [57]:
# Stacking
a = np.ones([2,3])
b = np.zeros([2,3])
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [70]:
a = np.array([(1,2,3),(1,2,3)],dtype=float)

# fromfunction
def kuadrat(a,b):
    return b**2
def penjumlahan(a,b):
    return a+b
b = np.fromfunction(kuadrat,(1,10),dtype = int)
c = np.fromfunction(penjumlahan,(4,4),dtype = float)
print(c)

# iterable array
iter = [i*2 for i in range(5)]
d = np.fromiter(iter,dtype=int)
print(d)

# multitype array
dtipe = [('nama','S255'),('tinggi',int)]
data = [('a',10),('b',7),('c',138)]

e = np.array(data,dtype=dtipe)
print(e)

[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]
[0 2 4 6 8]
[(b'a',  10) (b'b',   7) (b'c', 138)]
