In [1]:
import numpy as np
import random
# o = np.array([[1,4,9,11,2],
#              [4,1,3,10,8],
#              [9,3,1,5,10],
#              [11,10,5,1,7],
#              [2,8,10,7,1]])
#         ants = [
#             [[0,4,1,3,2],0.04],
#             [[1,2,3,4,0],0.058824],
#             [[2,1,0,4,3],0.0625]
#                ]



In [2]:
def generateJarakAntarKota(cities,koor):
    distance = []
    for i in range(len(cities)):
        temp=[]
        for j in range(len(cities)):
            #rumus jarak antar dua titik akar((x1-x2)**2 + (y1-y2)**2)
            d = np.sqrt((koor[i][0]-koor[j][0])**2+(koor[i][1]-koor[j][1])**2)
            temp.append(d)
        distance.append(temp)
    return  np.array(distance)
    


In [7]:
def semutBergerak(jarakKota,initPherom):

    # membuat informasi prior
    prior = 1/jarakKota
    # untuk menyimpan/menandai kota yang telah dilewati
    simpan = [None for i in range(len(jarakKota[0]))]
    # memilih kota pertama acak
    pilih = random.randint(0,len(jarakKota)-1)
    # tandai kota pertama telah dilewati
    simpan[pilih] = pilih
    # untuk menampung hasil kota terpilih
    hasil = [pilih]
    for n in range(len(jarakKota[0])-1):
        # total probabilitas kota yang mungkin dikunjungi
        total = 0
        for i in range(len(jarakKota[0])):
            if i not in simpan :
                total+= initPherom[pilih][i]*prior[pilih][i]
        print()
        print("Total = ",total)   
        
        # probabilitas masing masing rute
        prob = [None for x in range(len(jarakKota[0]))]    
        for j in range(len(jarakKota[0])):
            if j not in simpan : 
                prob[j] = initPherom[pilih][j]*prior[pilih][j]/total
                print(f"P({j}) = ",prob[j])

        # komulatif masing-masing rute
        komulatif = {}
        jml=0
        for k in range(len(prob)):
            if prob[k] != None:
                komulatif[k] = [jml,jml+prob[k]]
                jml+= prob[k]
                print(f"K({k}) = ",komulatif[k])

        # pilih acak
        acak = np.random.rand(1)
        for key,val in komulatif.items():
            #menentukan pilihan acak masuk ke komulatif mana
            if acak>val[0] and acak <= val[1]:
                pilih = key
                simpan[key] = key
                hasil.append(pilih)

    # menghitung delta hasil
    delta = 0
    for i in range(len(hasil)-1):
        delta+=jarakKota[hasil[i+1]][hasil[i]]
    delta = 1/delta
    
    return [hasil,delta]


def updatePheromone(ants,initPherom,rho):
    # evaporasi peromone
    evap = np.array(initPherom)*(1-rho)
    # update Pheromone
    for ant in ants:
        for j in range(len(ant[0])-1):
            evap[ant[0][j]][ant[0][j+1]] += ant[1]
    return evap
            
    
def antColony(iteration,numOfAnt,rho,kota,koor):
    
    jarakAntarKota = generateJarakAntarKota(kota,koor)
    print("Jarak Antar Kota\n",jarakAntarKota)

    initPherom = [[ 0 if i==j else 0.01 for i in range(len(jarakAntarKota))] 
                  for j in range(len(jarakAntarKota[0]))]
    print('Inisialisasi Konsentrasi Pheromone\n',np.array(initPherom))

    for i in range(iteration):
        print("\nITERASI ",i+1)
        ants=[]
        for j in range(numOfAnt):
        
            print('\nSemut ',j+1)
            temp = semutBergerak(jarakAntarKota,initPherom)
            print('Kota dilewati : ',temp[0],"Delta: ",temp[1])
            ants.append(temp)

            
        initPherom = updatePheromone(ants,initPherom,rho)
        print()
        print("Update Konsentrasi Pheromone\n",initPherom)
    
    


# cities = [0,1,2,3,4]
# koor = [(4.24, -1.45),
#         (1.81, 3.37),
#         (-2.59, 3.69),
#         (-5.72, -1.59),
#         (2.25, -4.02)]

inp = int(input("Masukkan jumlah kota : "))
cities = [i for i in range(inp) ]
koor = []
for j in range(inp):
    x = int(input(f"Masukkan titik x dari kota {j+1} : "))
    y = int(input(f"Masukkan titik y dari kota {j+1} : "))
    koor.append([x,y])

antColony(2,5,0.5,cities,koor)

Masukkan jumlah kota : 5
Masukkan titik x dari kota 1 : 1
Masukkan titik y dari kota 1 : 2
Masukkan titik x dari kota 2 : 3
Masukkan titik y dari kota 2 : 4
Masukkan titik x dari kota 3 : 5
Masukkan titik y dari kota 3 : 6
Masukkan titik x dari kota 4 : 7
Masukkan titik y dari kota 4 : 8
Masukkan titik x dari kota 5 : 9
Masukkan titik y dari kota 5 : 0
Jarak Antar Kota
 [[0.         2.82842712 5.65685425 8.48528137 8.24621125]
 [2.82842712 0.         2.82842712 5.65685425 7.21110255]
 [5.65685425 2.82842712 0.         2.82842712 7.21110255]
 [8.48528137 5.65685425 2.82842712 0.         8.24621125]
 [8.24621125 7.21110255 7.21110255 8.24621125 0.        ]]
Inisialisasi Konsentrasi Pheromone
 [[0.   0.01 0.01 0.01 0.01]
 [0.01 0.   0.01 0.01 0.01]
 [0.01 0.01 0.   0.01 0.01]
 [0.01 0.01 0.01 0.   0.01]
 [0.01 0.01 0.01 0.01 0.  ]]

ITERASI  1

Semut  1

Total =  0.005198857231489476
P(0) =  0.23325859341481317
P(1) =  0.2667414065851868
P(2) =  0.2667414065851868
P(3) =  0.23325859341481

C:\Users\Muhammad Alivian\AppData\Local\Temp\ipykernel_15112\3817576033.py:4: RuntimeWarning: divide by zero encountered in divide
  prior = 1/jarakKota
