In [1]:
import numpy as np
import random

In [2]:
def generateJarakAntarKota(cities,koor):
    distance = []
    for i in range(len(cities)):
        temp=[]
        for j in range(len(cities)):
            #rumus jarak antar dua titik akar((x1-x2)**2 + (y1-y2)**2)
            d = np.sqrt((koor[i][0]-koor[j][0])**2+(koor[i][1]-koor[j][1])**2)
            temp.append(d)
        distance.append(temp)
    return  np.array(distance)

In [4]:
def semutBergerak(jarakKota,initPherom):

    # membuat informasi prior
    prior = 1/jarakKota
    # untuk menyimpan/menandai kota yang telah dilewati
    simpan = [None for i in range(len(jarakKota[0]))]
    # memilih kota pertama acak
    pilih = random.randint(0,len(jarakKota)-1)
    # tandai kota pertama telah dilewati
    simpan[pilih] = pilih
    # untuk menampung hasil kota terpilih
    hasil = [pilih]
    for n in range(len(jarakKota[0])-1):
        # total probabilitas kota yang mungkin dikunjungi
        total = 0
        for i in range(len(jarakKota[0])):
            if i not in simpan :
                total+= initPherom[pilih][i]*prior[pilih][i]
        print()
        print("Total = ",total)   
        
        # probabilitas masing masing rute
        prob = [None for x in range(len(jarakKota[0]))]    
        for j in range(len(jarakKota[0])):
            if j not in simpan : 
                prob[j] = initPherom[pilih][j]*prior[pilih][j]/total
                print(f"P({j}) = ",prob[j])
        print()
        # komulatif masing-masing rute
        komulatif = {}
        jml=0
        for k in range(len(prob)):
            if prob[k] != None:
                komulatif[k] = [jml,jml+prob[k]]
                jml+= prob[k]
                print(f"K({k}) = ",komulatif[k])

        # pilih acak
        acak = np.random.rand(1)
        for key,val in komulatif.items():
            #menentukan pilihan acak masuk ke komulatif mana
            if acak>val[0] and acak <= val[1]:
                pilih = key
                simpan[key] = key
                hasil.append(pilih)

    # menghitung delta hasil
    delta = 0
    for i in range(len(hasil)-1):
        delta+=jarakKota[hasil[i+1]][hasil[i]]
    delta = 1/delta
    
    return [hasil,delta]


def updatePheromone(ants,initPherom,rho):
    # evaporasi peromone
    evap = np.array(initPherom)*(1-rho)
    # update Pheromone
    for ant in ants:
        for j in range(len(ant[0])-1):
            evap[ant[0][j]][ant[0][j+1]] += ant[1]
    return evap
            
    
def antColony(iteration,numOfAnt,rho,kota,koor):
    
    jarakAntarKota = generateJarakAntarKota(kota,koor)
    print("Jarak Antar Kota\n",jarakAntarKota)

    initPherom = [[ 0 if i==j else 0.01 for i in range(len(jarakAntarKota))] 
                  for j in range(len(jarakAntarKota[0]))]
    print('Inisialisasi Konsentrasi Pheromone\n',np.array(initPherom))

    for i in range(iteration):
        print("\nITERASI ",i+1)
        ants=[]
        for j in range(numOfAnt):
        
            print('\nSemut ',j+1)
            temp = semutBergerak(jarakAntarKota,initPherom)
            print('Kota dilewati : ',temp[0],"Delta: ",temp[1])
            ants.append(temp)

            
        initPherom = updatePheromone(ants,initPherom,rho)
        print()
        print("Update Konsentrasi Pheromone\n",initPherom)



inp = int(input("Masukkan jumlah kota : "))
cities = [i for i in range(inp) ]
koor = []
for j in range(inp):
    x = int(input(f"Masukkan titik x dari kota {j+1} : "))
    y = int(input(f"Masukkan titik y dari kota {j+1} : "))
    koor.append([x,y])

antColony(2,3,0.5,cities,koor)

Masukkan jumlah kota : 4
Masukkan titik x dari kota 1 : 0
Masukkan titik y dari kota 1 : 0
Masukkan titik x dari kota 2 : 2
Masukkan titik y dari kota 2 : 5
Masukkan titik x dari kota 3 : 4
Masukkan titik y dari kota 3 : 5
Masukkan titik x dari kota 4 : 7
Masukkan titik y dari kota 4 : 6
Jarak Antar Kota
 [[0.         5.38516481 6.40312424 9.21954446]
 [5.38516481 0.         2.         5.09901951]
 [6.40312424 2.         0.         3.16227766]
 [9.21954446 5.09901951 3.16227766 0.        ]]
Inisialisasi Konsentrasi Pheromone
 [[0.   0.01 0.01 0.01]
 [0.01 0.   0.01 0.01]
 [0.01 0.01 0.   0.01]
 [0.01 0.01 0.01 0.  ]]

ITERASI  1

Semut  1

Total =  0.00450334328974986
P(1) =  0.4123499503129515
P(2) =  0.3467951516023128
P(3) =  0.24085489808473565

K(1) =  [0, 0.4123499503129515]
K(2) =  [0.4123499503129515, 0.7591451019152643]
K(3) =  [0.7591451019152643, 1.0]

Total =  0.006961161351381841
P(2) =  0.7182709533097468
P(3) =  0.28172904669025317

K(2) =  [0, 0.7182709533097468]
K(3) =

C:\Users\Muhammad Alivian\AppData\Local\Temp\ipykernel_7204\4000944321.py:4: RuntimeWarning: divide by zero encountered in divide
  prior = 1/jarakKota
