In [1]:
import numpy as np 
x = [5,-10,4,-20,0,11]
print(bin(31))

0b11111


In [2]:
# y = -x**2-5x+5

popoulasi = [
             [1,0,0,1,0,1],
             [0,0,1,0,1,0],
             [1,0,0,1,0,0],
             [0,1,0,1,0,0],
             [1,0,0,0,0,0],
             [1,0,1,0,1,1]]

temp = []
for i in x :
    temp.append(-i**2-5*i+5)
print('test',temp)
sum(temp)

temp = np.array(temp)
print(sum(temp))
temp = temp+296 #kerena negatif maka ditambah nilai terkecil dan (di tambah epsilon 1) agar probabilitas tidak 0
print(temp)
print(sum(temp))
prob = temp/sum(temp)
print(prob)

test [-45, -45, -31, -295, 5, -171]
-582
[251 251 265   1 301 125]
1194
[0.21021776 0.21021776 0.22194305 0.00083752 0.2520938  0.10469012]


In [3]:
# setelah menentuakn ruang dan mendapatkan nilai dari percobaan
# selanjutnya dilakukan crossover dengan menukar nilai berpasangan dengan index acak

In [4]:
# elitist strategy = menjaga kromosom yang memiliki nilai fitness tinggi

## Code

In [5]:
def convertToBin(num):
    hsl = np.zeros(6,int)
    if num >= 0 :
        hsl[0] = 1
    else:
        num = num*-1 
    i=-1
    while num != 0:
        hsl[i]=num%2
        num //= 2
        i-=1
    return hsl
    
a = convertToBin(11)

def convertToNum(biner):
    hasil = 0
    for i in range(-1,-6,-1):
        hasil+=biner[i]*2**((i*-1)-1)
    if biner[0] == 0 :
        hasil= -hasil
    return hasil
        

convertToNum(a)

11

In [6]:
def generatePopulation(individu):
    population = np.zeros([individu,6],dtype=int)
    for i in range(individu):
        population[i]=convertToBin(np.random.randint(-31,31))
    return population
pop = generatePopulation(6)
print(pop)
for i in pop:
    print(convertToNum(i))

[[1 0 1 0 1 0]
 [1 0 0 1 0 0]
 [1 1 1 1 1 0]
 [1 1 1 0 0 1]
 [0 1 1 0 1 0]
 [1 0 0 0 1 0]]
10
4
30
25
-26
2


In [7]:
def fitnessFunc(x):
    return 2*x**2-50*x+20

def calculateFitness(population):
    fitness = np.zeros(len(population),int)
    for i in range(len(population)):
        fitness[i] = fitnessFunc(convertToNum(population[i]))
    return fitness

popoulasi = [
             [1,0,0,1,0,1],
             [0,0,1,0,1,0],
             [1,0,0,1,0,0],
             [0,1,0,1,0,0],
             [1,0,0,0,0,0],
             [1,0,1,0,1,1]]

fitness = calculateFitness(popoulasi)

print(fitness)

[-180  720 -148 1820   20 -288]


In [8]:
def selection(fitness):
    
    fitness = fitness+min(fitness)*-1+1 #kerena negatif maka ditambah nilai terkecil dan (di tambah epsilon 1) agar probabilitas tidak 0
    totalFitness = np.sum(fitness)
    print('totalFitness = ',totalFitness)
    
    probIndividu = fitness/totalFitness
    print('probabilitas',probIndividu)
    sizeIndividu = len(fitness)
    komulatif = np.zeros(sizeIndividu+1)
    
    for i in range(sizeIndividu):
        komulatif[i+1] = komulatif[i]+probIndividu[i]
        
    print('komulatif',komulatif)
    
    count = 0
    newProb = np.zeros(sizeIndividu,int)
    for j in range(sizeIndividu):
        roulette = np.random.rand(1)
        for i in range(sizeIndividu+1):
            if roulette > komulatif[i] and roulette <= komulatif[i+1]:
                newProb[count]=i
        count += 1
    return newProb
    
index = selection(fitness)
print(index)

totalFitness =  3678
probabilitas [2.96356716e-02 2.74333877e-01 3.83360522e-02 5.73409462e-01
 8.40130506e-02 2.71886895e-04]
komulatif [0.         0.02963567 0.30396955 0.3423056  0.91571506 0.99972811
 1.        ]
[3 3 1 1 3 3]


In [9]:
def newPopulation(idx,population):
    newP = np.zeros_like(population)
    for i in range(len(idx)):
        newP[i] = population[idx[i]]
    return newP
newPop = newPopulation(index,pop)
print(pop)
print("New Populasi dari hasil seleksi:\n",newPop)

[[1 0 1 0 1 0]
 [1 0 0 1 0 0]
 [1 1 1 1 1 0]
 [1 1 1 0 0 1]
 [0 1 1 0 1 0]
 [1 0 0 0 1 0]]
New Populasi dari hasil seleksi:
 [[1 1 1 0 0 1]
 [1 1 1 0 0 1]
 [1 0 0 1 0 0]
 [1 0 0 1 0 0]
 [1 1 1 0 0 1]
 [1 1 1 0 0 1]]


In [10]:
# reverse/dibalik
def crossover(population):
    newP = population.copy()
    (numOfIndividu,numOfBit) = population.shape
    for i in range(numOfIndividu):
        ind1,ind2 = np.random.randint(numOfBit),np.random.randint(numOfBit)
        print(ind1,ind2)
        if ind1 <= ind2 :
            temp = ind2 
            for j in range(ind1,ind2+1):
                newP[i,j] = population[i,temp]
                temp-=1
        else:
            temp = ind1
            for j in range(ind2,ind1+1):
                newP[i,j] = population[i,temp]
                temp-=1
    return newP
 
print(newPop)
populasi = crossover(newPop)
print("Hasil Crossover :\n",populasi)

[[1 1 1 0 0 1]
 [1 1 1 0 0 1]
 [1 0 0 1 0 0]
 [1 0 0 1 0 0]
 [1 1 1 0 0 1]
 [1 1 1 0 0 1]]
3 0
5 0
2 3
1 2
1 1
5 0
Hasil Crossover :
 [[0 1 1 1 0 1]
 [1 0 0 1 1 1]
 [1 0 1 0 0 0]
 [1 0 0 1 0 0]
 [1 1 1 0 0 1]
 [1 0 0 1 1 1]]


In [11]:
# import random

# def crossover_sebagian_acak(kromosom1, kromosom2):
#     panjang_kromosom = len(kromosom1)
#     i = random.randint(0, panjang_kromosom - 2)
#     j = random.randint(i + 1, panjang_kromosom - 1)
#     anak1 = kromosom1[:i] + kromosom2[i:j] + kromosom1[j:]
#     anak2 = kromosom2[:i] + kromosom1[i:j] + kromosom2[j:]
#     return anak1, anak2

# def crossover2(data):
#     hasil = []
#     for i in range(0,len(data),2):
#         a, b = (crossover_sebagian_acak(data[i], data[i+1]))
#         hasil.append(a)
#         hasil.append(b)
#     return hasil

# populasi2 = crossover2(newPop)
# print("Hasil Crossover :\n",populasi2)

In [12]:
# digeser
def mutation(population):
    newP = population.copy()
    (numOfIndividu,numOfBit) = population.shape
    for i in range(numOfIndividu):
        ind1,ind2 = np.random.randint(numOfBit),np.random.randint(numOfBit)
        print(ind1,ind2)
        newP[i,ind1],newP[i,ind2] = newP[i,ind2],newP[i,ind1]
    return newP
print(populasi)
mutasi = mutation(populasi)
print("Hasil Mutasi : \n",mutasi)

[[0 1 1 1 0 1]
 [1 0 0 1 1 1]
 [1 0 1 0 0 0]
 [1 0 0 1 0 0]
 [1 1 1 0 0 1]
 [1 0 0 1 1 1]]
3 5
4 2
2 0
2 1
0 1
0 2
Hasil Mutasi : 
 [[0 1 1 1 0 1]
 [1 0 1 1 0 1]
 [1 0 1 0 0 0]
 [1 0 0 1 0 0]
 [1 1 1 0 0 1]
 [0 0 1 1 1 1]]


In [13]:
def geneticAlgoritm(numOfPopulation,generation):
    population = generatePopulation(numOfPopulation)
    
    print("Inisialisasi Populasi :\n",population)
    for i in population:
        print(convertToNum(i))
    
    for i in range(generation):
        print(f"Generasi-{i}")
        nilaiFitness = calculateFitness(population)
        print("Fitness",nilaiFitness)
        newInd = selection(nilaiFitness)
        print("Indeks hasil populasi seleksi :",newInd)
        population = newPopulation(newInd,population)
        print("Individu Hasil Seleksi :\n",population)
        population = crossover(population)
        print("Hasil crossover :\n",population)
        population = mutation(population)
        print("Hasil mutasi :\n",population)
    return population
    
geneticAlgoritm(8,1)

Inisialisasi Populasi :
 [[0 1 1 1 0 0]
 [1 0 1 1 1 0]
 [0 0 1 1 1 1]
 [1 1 1 1 0 1]
 [1 1 1 1 0 1]
 [0 0 1 0 1 0]
 [0 1 0 0 0 0]
 [1 1 0 1 0 1]]
-28
14
-15
29
29
-10
-16
21
Generasi-0
Fitness [2988 -288 1220  252  252  720 1332 -148]
totalFitness =  8640
probabilitas [3.79282407e-01 1.15740741e-04 1.74652778e-01 6.26157407e-02
 6.26157407e-02 1.16782407e-01 1.87615741e-01 1.63194444e-02]
komulatif [0.         0.37928241 0.37939815 0.55405093 0.61666667 0.67928241
 0.79606481 0.98368056 1.        ]
Indeks hasil populasi seleksi : [5 0 6 0 6 2 5 0]
Individu Hasil Seleksi :
 [[0 0 1 0 1 0]
 [0 1 1 1 0 0]
 [0 1 0 0 0 0]
 [0 1 1 1 0 0]
 [0 1 0 0 0 0]
 [0 0 1 1 1 1]
 [0 0 1 0 1 0]
 [0 1 1 1 0 0]]
2 4
4 3
0 0
1 5
4 2
0 2
0 4
5 0
Hasil crossover :
 [[0 0 1 0 1 0]
 [0 1 1 0 1 0]
 [0 1 0 0 0 0]
 [0 0 0 1 1 1]
 [0 1 0 0 0 0]
 [1 0 0 1 1 1]
 [1 0 1 0 0 0]
 [0 0 1 1 1 0]]
1 0
0 0
1 5
2 0
2 0
4 3
0 3
4 2
Hasil mutasi :
 [[0 0 1 0 1 0]
 [0 1 1 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 1 1 1]
 [0 1 0 0 0 0]
 [1 

array([[0, 0, 1, 0, 1, 0],
       [0, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 0]])

In [14]:
def GAwithElitist(numOfPopulation,generation):
    population = generatePopulation(numOfPopulation)
    print("Inisialisasi Populasi :\n",population)
    for i in range(generation):
        print(f"Generasi-{i}")
        # algoritma genetik
        oldPopulation = population.copy()
        nilaiFitness = calculateFitness(population)
        maxFitness = np.max(nilaiFitness)
        newInd = selection(nilaiFitness)
        population = newPopulation(newInd,population)
        population = crossover(population)
        population = mutation(population)
        
        
         #elitist strategy
        nilaiFitnessOld = calculateFitness(oldPopulation)
        indOld = np.argsort(nilaiFitnessOld)
        nilaiFitnessNew = calculateFitness(population)
        indNew = np.argsort(nilaiFitnessNew)
        
        print("Populasi lama = \n",oldPopulation)
        print("Fitness lama = \n",nilaiFitnessOld)
        print("Populasi baru = \n",population)
        print("Fitness baru = \n",nilaiFitnessNew)
        
        populationOld = newPopulation(indOld[0:numOfPopulation//2],oldPopulation)
        populationNew = newPopulation(indNew[0:numOfPopulation//2],population)
        
        population[0:numOfPopulation//2] = populationOld[0:numOfPopulation//2]
        population[numOfPopulation//2:numOfPopulation] = populationNew[0:numOfPopulation//2]
        
        print("Elitist = \n",population)
        
GAwithElitist(6,2)

Inisialisasi Populasi :
 [[1 0 0 0 0 1]
 [1 1 0 1 1 1]
 [0 1 0 0 0 0]
 [0 1 0 1 1 0]
 [0 0 1 1 0 1]
 [0 0 1 1 0 0]]
Generasi-0
totalFitness =  5674
probabilitas [7.93091294e-03 1.76242510e-04 2.47620726e-01 3.80860063e-01
 1.90518153e-01 1.72893902e-01]
komulatif [0.         0.00793091 0.00810716 0.25572788 0.63658795 0.8271061
 1.        ]
0 2
1 1
3 0
3 0
4 2
4 0
5 3
1 4
0 3
1 4
0 4
0 3
Populasi lama = 
 [[1 0 0 0 0 1]
 [1 1 0 1 1 1]
 [0 1 0 0 0 0]
 [0 1 0 1 1 0]
 [0 0 1 1 0 1]
 [0 0 1 1 0 0]]
Fitness lama = 
 [ -28  -72 1332 2088 1008  908]
Populasi baru = 
 [[0 1 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 1 1 1 0 0]
 [1 1 0 1 0 0]]
Fitness baru = 
 [1332  128  548  548 2988 -180]
Elitist = 
 [[1 1 0 1 1 1]
 [1 0 0 0 0 1]
 [0 0 1 1 0 0]
 [1 1 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 1 0 0 0]]
Generasi-1
totalFitness =  2390
probabilitas [4.56066946e-02 6.40167364e-02 4.55648536e-01 4.18410042e-04
 1.29288703e-01 3.05020921e-01]
komulatif [0.         0.04560669 0.10962343 0.565271